### ISSUE TITLE
Add about us page

### ISSUE THREAD

**Issue by kushagra-singhh** [princekhunt/privateping#10]
**Is your feature request related to a problem? Please describe.**
There is no about us page in the website.

**Describe the solution you'd like**
Creating about us page for the website.

**Comment by princekhunt** [comment]
I do not think about us page is really necessary.
We're recognising contributors in humans.txt file already.

Checkout [humans.txt](https://privateping.bytespot.tech/humans.txt)

Check source file - [source humans.txt](https://github.com/princekhunt/privateping/blob/main/registration/templates/registration/humans.txt)

**Comment by kushagra-singhh** [comment]
okay.
