### ISSUE TITLE
Adding light/dark theme

### ISSUE THREAD

**Issue by Dhiv123** [princekhunt/privateping#11]
Adding Light/Dark Themes

I would like to propose the addition of dark theme to this project. 
This feature will enhance user experience by allowing users to switch between light and dark modes according to their preferences.
 
Please assign  this issue to me under SSOC'24.

**Comment by princekhunt** [comment]
Alright @Dhiv123 

Good luck.

**Comment by princekhunt** [comment]
Any update ?

**Comment by Dhiv123** [comment]
Will be done by tomorrow

**Comment by tanuj437** [comment]
Can i Take over the task for adding light/dark mode
Under SSOC'24

**Comment by princekhunt** [comment]
Sure
