### ISSUE TITLE
On login page, user is able to click on next, even if username field is blank.

### ISSUE THREAD

**Issue by princekhunt** [princekhunt/privateping#14]
**Describe the bug**
On Login page, a user can move to password field by clicking next button, even if the username field is empty.

**To Reproduce**
1. Go to https://privateping.bytespot.tech 
2. Click on Login
3. Keep the username field empty and click on next
4. See error, you will see the password field.

**Expected behavior**
A clear and concise error should be displayed that, username must be entered before moving ahead to enter the password.

**Comment by HWKDS** [comment]
Hey @princekhunt I see this issue, and I would like to contribute to this issue by solving it. 
Can you assign this issue to me under SSOC'24.

**Comment by sudh182004** [comment]
Hi @princekhunt 

Actually, I want to know which database you are using for login and signup authentication so that I can provide you with more secure and verified suggestions.

**Comment by sudh182004** [comment]
By the way, my name is Sudhanshu Dwivedi, and I have already worked on many projects regarding authentication systems. You can check my authentication work here https://drive.google.com/drive/folders/11ffS11w9PChXLO6QRLgEz2iVqQx8mm_5

**Comment by princekhunt** [comment]
Hi @sudh182004 ,
Thank you for the interest, we assign Issues based on First come first serve.
You can lookup other unassigned issues.

**Comment by princekhunt** [comment]
@HWKDS Thanks.
Go for it.

**Comment by sudh182004** [comment]
@princekhunt 

No issue. However, if you need any help regarding this in the future, you can contact me. I would be happy to contribute to your project. Here is my LinkedIn I'd https://www.linkedin.com/in/sudhanshu-dwivedi-98a5672b5?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app

**Comment by princekhunt** [comment]
@sudh182004 I am more than happy to invite contributors like you.

I recommend you to try and use this project, https://privateping.bytespot.tech and create new issues of bugs, enhancements and feature request.

To answer your question, we're using Postgres database.

**Comment by sudh182004** [comment]
@princekhunt 

Thank you for the invitation! I will definitely check out the project and contribute by reporting bugs, suggesting enhancements, and requesting features.

**Comment by princekhunt** [comment]
Now an error message is shown when user leaves the username field empty.
