### ISSUE TITLE
Improve UI of dropdown menu

### ISSUE THREAD

**Issue by princekhunt** [princekhunt/privateping#15]
**Is your feature request related to a problem? Please describe.**
I am proposing to improve the UI of dropdown menu of selecting the time, on chat page.

**Describe the solution you'd like**
A css can be used to improve the dropdown manu, that can make it user interactive.

**Comment by princekhunt** [comment]
Go on.
Good luck.

**Comment by princekhunt** [comment]
Any update @mryashsinghal

**Comment by mryashsinghal** [comment]
Hi @princekhunt 
I'm currently working on the task and making progress; I'll provide a detailed update soon.

**Comment by mryashsinghal** [comment]
I wanted to let you know that my recent UI improvements to the dropdown menu on the chat page have been successfully done. I’ve verified that everything is working as expected.

**Comment by princekhunt** [comment]
Kindly make the pull request.

**Comment by mryashsinghal** [comment]
I have submitted a pull request that you have already merged.
