### ISSUE TITLE
Improve "Connect to User" modal

### ISSUE THREAD

**Issue by princekhunt** [princekhunt/privateping#16]
**Is your feature request related to a problem? Please describe.**
When user clicks on Add user button on the homepage, a modal opens, where two fields are available.
This form UI can be improved,

**Describe the solution you'd like**
A css tweaks can be used to improve the modal as well as the form.

**Comment by HemantKr071** [comment]
Hii @princekhunt ,
I would like the work on this feature.
Please assign me this issue.
Thanks

**Comment by SNEHA-81** [comment]
@princekhunt assign me this work under ssoc

**Comment by Mayureshd-18** [comment]
![image](https://github.com/princekhunt/privateping/assets/98738585/8008e1f0-7795-434a-834a-39d73f4b20f1)

@princekhunt  I have attached my changed UI. Please assign this issue.

**Comment by princekhunt** [comment]
@SNEHA-81 Please go ahead.
@Mayureshd-18 We assign issue based on first come first serve basis. However you've presented a good design.
If something goes wrong, then I'll assign it to you @Mayureshd-18 

Note: Kindly start working when issue is assigned to save time.

Thanks

**Comment by princekhunt** [comment]
Any update @SNEHA-81 ?

**Comment by SNEHA-81** [comment]
@princekhunt yeah working, will get it done shortly.

**Comment by princekhunt** [comment]
@SNEHA-81 Kindly make PR before End of the day, else issue will be assigned to @Mayureshd-18

**Comment by princekhunt** [comment]
@Mayureshd-18 Are you interested in this issue? as you've already made changes.

**Comment by Mayureshd-18** [comment]
@princekhunt I will not be able to make a pr for 2 days. If anyone else is interested then you can assign him. Else after 2 days I will create a pr
