### ISSUE TITLE
Different language

### ISSUE THREAD

**Issue by MetiUmashri** [princekhunt/privateping#18]
Why not add "नमस्ते" in different languages evolving after delay of every 10 seconds

This feature can help to increase the interactivity and is considered under the feature enhancement request.

I kindly request you to assign this feature enhancement to me.

<img width="959" alt="image" src="https://github.com/princekhunt/privateping/assets/97387069/1513fe6b-e7c6-4bc6-89f8-38e7c382ee68">

**Comment by princekhunt** [comment]
@MetiUmashri That would be great.

**Comment by princekhunt** [comment]
Any update @MetiUmashri ?

**Comment by MetiUmashri** [comment]
Yes sorry for the delay I have raised a pull requeat
