### ISSUE TITLE
Don't allow user to click on send button, while message box is empty

### ISSUE THREAD

**Issue by princekhunt** [princekhunt/privateping#24]
**Describe the bug**
On chat page, When user has not typed any message, user is able to click on send button, and falls into infinite loading.

**To Reproduce**
1. Go to chatting page
2. Do not type any message
3. Click on send button
4. See, you'll see button loading infinitely. 

**Expected behavior**
A send button should be disabled until user type any message.

**Screenshots**
<img width="106" alt="Loading" src="https://github.com/princekhunt/privateping/assets/63849074/e7b3d4a0-ca32-4056-810b-0065283697cf">

**Comment by sudarshankakde** [comment]
make input field required and it's done!

**Comment by sudarshankakde** [comment]
> make input field required and it's done!

also input filed should be textarea instead of normal input filed as message can be long

**Comment by snipher-marube** [comment]
assign this to me is not already fixed

**Comment by princekhunt** [comment]
Sorry, it's fixed.
