### ISSUE TITLE
Disable Right click on all pages of privateping app.

### ISSUE THREAD

**Issue by princekhunt** [princekhunt/privateping#25]
**Is your feature request related to a problem? Please describe.**
We're trying to app more tight and secure, hence it would be beneficial to block the right click while a user is chatting or using any other functionality

**Describe the solution you'd like**
A javascript can be implemented which blocks the right click on the app.

**Comment by sudarshankakde** [comment]
let me do this too... 
assing me!

**Comment by sudarshankakde** [comment]
we already have disabled PrtScn. By using a similar approach we can disable above mentions keys as well as we can disable contextmenu(right click)

**Comment by sudarshankakde** [comment]
PR created!

**Comment by sudarshankakde** [comment]
Close the issue it has been merged
