### ISSUE TITLE
Implement hCaptcha in anonymous login

### ISSUE THREAD

**Issue by princekhunt** [princekhunt/privateping#30]
**Is your feature request related to a problem? Please describe.**
A user can create an anonymous account, by just one click. To prevent bots doing that, I propose to add captcha. User has to pass through human verification.

**Describe the solution you'd like**
Privateping is privacy oriented application, hence it's decided to use hcaptcha service.
When user clicks on `Anonymous Direct Login` Button, currently we move them to`/AnonymousDirectLogin` and perform mouse hover check. Now we will replace it with the captcha. and on successful captcha verification, user should be able to create an anonymous account.

**Comment by Mayureshd-18** [comment]
We can use google recaptacha  or a basic django-simpel-captcha. If you prefer to use google  recaptcha, I would need the keys from the [recaptcha website](https://www.google.com/recaptcha/about/). Else we can directly use simple django captcha like the image below
![image](https://github.com/princekhunt/privateping/assets/98738585/e119aa86-fc74-42ec-a7fb-d9a92dc0001e)

**Comment by princekhunt** [comment]
Can't we use [hCaptcha](https://www.hcaptcha.com/) ?

**Comment by Mayureshd-18** [comment]
Ya sure that would work too. If you can assign it, I will be able to see the best possible way and start working on it.

**Comment by princekhunt** [comment]
Alright. 
Go on.

**Comment by Mayureshd-18** [comment]
@princekhunt Hello. I have the prototype ready. Just a few tweaks are remaining. Please review the attached image and confirm whether anything more is needed. 
![image](https://github.com/princekhunt/privateping/assets/98738585/b9dce309-1265-4123-bfbe-5aef2a4e9679)



Also, it would be better if you could provide me with the keys needed for Captcha as it would keep things under your control. If you can't share them here, you can share them on LinkedIn or mail me. 

Regards.

**Comment by Mayureshd-18** [comment]
Yeah already done that. I was just asking if I should replace my keys or you would. 
Thank you.
 Just replace the keys before deploying to production.

Regards

**Comment by princekhunt** [comment]
Yes, will update in prod, kindly make pr.
will test the functionality and design before heading.
