### ISSUE TITLE
Add comments in chat/views.py to make more developer friendly.

### ISSUE THREAD

**Issue by princekhunt** [princekhunt/privateping#31]
**Is your feature request related to a problem? Please describe.**
I would like to propose to add appropriate comments for block of code, for developers to understand and review.

**Describe the solution you'd like**
Add single line comments in each functions and multiline comments in starting of each function. That will help understanding the purpose of the function.

**Comment by avneeetk** [comment]
I want to work on the issue. Kindly assign it to me!

**Comment by princekhunt** [comment]
Are you still on it ?

**Comment by avneeetk** [comment]
After reviewing the file, I see that there are already some comments present.
Could you please provide some guidance on the following:
Are there specific areas in the code where you feel the current comments are insufficient or unclear?

I am new to open source so it wld be really helpful if you can guide
