### ISSUE TITLE
Add comments in registration/views.py to make more developer friendly

### ISSUE THREAD

**Issue by princekhunt** [princekhunt/privateping#32]
**Is your feature request related to a problem? Please describe.**
I would like to propose to add appropriate comments for block of code, for developers to understand and review.

**Describe the solution you'd like**
Add single line comments in each functions and multiline comments in starting of each function. That will help understanding the purpose of the function.

**Comment by Mayureshd-18** [comment]
Would like to work on it

**Comment by princekhunt** [comment]
Okay, go on.
