### ISSUE TITLE
Any new creative approach to generate unique user-friendly username ?

### ISSUE THREAD

**Issue by princekhunt** [princekhunt/privateping#33]
**Is your feature request related to a problem? Please describe.**
Currently we're using object list and verbs list, and combining random combination to generate unique username for the user on anonymous login.

Is there any new creative approach to make it user-friendly ?

**Comment by sudarshankakde** [comment]
> Combining adjectives with nouns along with random numbers can give us some pretty awsome usernames.

### Explanation  - 
we can set  Word Lists for adjectives and nouns 
for example - 
```
adjectives = ["Happy", "Clever", "Curious", "Radiant", "Bold", "Swift", "Dreamy", "Magical"]
nouns = ["Panda", "Fox", "Dolphin", "Unicorn", "Star", "Explorer", "Wizard", "Ninja"]
```
and add a random number at last which can define username unique as well as we can improve username generation possibility by adding more words to word list.

**Comment by Mayureshd-18** [comment]
@princekhunt  What do you mean by more user-friendly exactly? Can you explain through an example whats in your mind?

**Comment by Mayureshd-18** [comment]
Why are we taking username input from the users itself?

**Comment by princekhunt** [comment]
We're trying to make Anonymous login fast, and less complex, while maintaining anonymity. That's why it'll be good approach to generate username from backend and assign it to a user.

**Comment by Tapeline** [comment]
Honestly, I don't really see a problem there. This generation is already very good (except that it could potentially go into an infinite loop). If you want to change it anyways, you might want to take a look at Docker container name generation. It is essentially *adjective* + *scientist/famous person*, which results into something like *elegant_gauss*

**Comment by princekhunt** [comment]
Thank you @Tapeline @Mayureshd-18 for your suggestions in this issue. We're sticking with what we already have.
