### ISSUE TITLE
Organizing merging of dev to main

### ISSUE THREAD

**Issue by princekhunt** [princekhunt/privateping#38]
Dear @snipher-marube, Your contributions are really great, and I appreciate your work. However, there's an issue, your pull requests contain many changes that are unrelated to the PR description. This makes it difficult to merge all the committed files into the main branch. I need to filter and work on specific changes separately.

I would suggest to Stick to one feature or title per pull request.
and Feel free to create multiple pull requests and branches if needed.

For example, in this PR, [Fix Development Server Warnings and Enhance Project Configuration](https://github.com/princekhunt/privateping/pull/7), change only the settings.

This separation will help everyone understand why a specific change was made.

Looking forward to your new fresh PRs, such as:
1. Fix Development Server Warnings
2. Make the Code DRY
3. Admin Customization

Currently closing dev1.0 and dev branch unmerged, due to multiple conflicts.

**Comment by snipher-marube** [comment]
Am so sorry for that I will make sure to be specific to my PRs onwards as suggested. Thank you
