### ISSUE TITLE
hCaptcha Sitekey Configuration Issue: Incorrect Sitekey Error

### ISSUE THREAD

**Issue by snipher-marube** [princekhunt/privateping#51]
**Description of the the bug**
We are encountering an issue with the hCaptcha integration on the development site when trying to login anonymously where the CAPTCHA validation fails due to an incorrect sitekey configuration. The error message displayed is "The sitekey for this hCaptcha is incorrect. Please contact the site admin if you see this."  I have added my own sitekey and secret key to my .env file  which i obtained form hcaptcha website [here](https://dashboard.hcaptcha.com/) after signing up to obtain the keys.

**To Reproduce**
1. Navigate to the development site.
2. Click on 'Anonymously Direct Login'

**Expected behavior**
The hCaptcha should display correctly and allow the user to complete the CAPTCHA challenge, confirming they are human..

**Screenshots**
![Screenshot from 2024-06-24 05-28-42](https://github.com/princekhunt/privateping/assets/61820565/ef57fbde-c179-49d0-aa1c-8ffeb9e55125)

**Desktop**
 - OS: Kali linux Debian Distro
 - Browser: Brave, Chrome

**Additional context**

- This issue appears to be related to the hCaptcha sitekey configuration in the application.
- Ensure that the correct sitekey is configured in the application's settings or environment variables.
- Verify that the sitekey used corresponds to the correct environment (development, staging, production).

**Impact**

This issue prevents users from successfully passing the browser check, potentially hindering access to the site and causing a poor user experience.

Thank you for addressing this issue promptly.

**Comment by princekhunt** [comment]
That is because, settings is not able to find site key and secret in the .env file (in dev mode).
we need to add test keys in .env file to run dev successfully.

For that instructions can be added in readme

**Comment by princekhunt** [comment]
I have made new push to main, where I updated readme, could you please update as defined and check if the issue still persists.

**Comment by snipher-marube** [comment]
Yes now it is resolved thank you

**Comment by snipher-marube** [comment]
Yes now it is resolved thank you
