### ISSUE TITLE
Updating contributing.md

### ISSUE THREAD

**Issue by Priyanshu2631** [princekhunt/privateping#9]
A contributing.md file is helpful for contributors for collaborating towards the projects alongwith adding instructions on how to contribute. Please assign me the issue under SSOC'24

**Comment by princekhunt** [comment]
There is already. 
Checkout - [contributing.md](https://github.com/princekhunt/privateping/blob/main/CONTRIBUTING.md)

If you find any updations are required, let me know, then I'll assign it to you.

**Comment by Priyanshu2631** [comment]
@princekhunt I wanna add contribution instructions using GitHub Desktop, and links on instructions how to fork,etc and minor changes

**Comment by princekhunt** [comment]
Alright!

Go on.
